---
title: Sample
author: Anders Schmidt
date: '2018-07-13'
slug: sample
categories: []
tags: []
header:
  caption: ''
  image: ''
---


On my way to design a third and fourth clinical trial I found it useful to reflect on the way the previous studies were designed and what considerations I have made. Randomized trials are only as good as they are designed - and important considerations must be made prior to the initiation of the project. Often recruitment of patients may last for years and therefore a careful plan is needed to enhance the scientific outcome of the study. Conventional randomized trials are designed so that they will provide a meaningful answer on its own (definitive stand-alone study), adresses a superiority question, allocates patients in a 1:1 ratio to two parallel study groups.

# Choosing the best primary endpoint
Since the sample size estimation and the conclusion of the study is based on what was choosen as primary endpoint it is of outmost importance to deside on the primary endpoint a priori. Also, the endpoint must be meaningful to clinicians, so that the results can be implemented in practise and provide not just evidence but useful information. The primary endpoint must be a variable were it is meaningful to calculate and detect a difference, i.e. **effect size**. One must deside on choosing an endpoint that is realistic to clinicians or an endpoint that is realistic to the current evidence and in-line with previous studies. Ideal the endpoint is realistic to both. As a further guidance the principe of "the minimal difference important to patients."

For the cardioversion trials we desided on using **cardioversion outcome** since it provides crusial benefits: 

   - It a variable, were a difference can be meassured and is clinical meaningful
   - It a dicotomous outcome, which is very robust, and can be documented on an electrocardiogram

For the individual trials a taget difference must be determined.      
         
# Sample size estimation

For estimating the trial size I used the `power.prop.test` function in *R*: 

```{r echo=TRUE, message=FALSE, warning=FALSE, paged.print=FALSE}

power.prop.test(p1 = 0.95, 
                p2 = 0.85, 
                sig.level = 0.05,
                power = 0.80, 
                alternative = c("two.sided"),
                n = NULL
                )

```
