---
title: My notes on effect size and sample size estimations for clinical trials
author: Anders S. Schmidt, M.D.
date: '2018-07-13'
slug: sample
categories: []
tags: []
header:
  caption: ''
  image: ''
---


<<<<<<< HEAD
On my way to design a third and fourth clinical trial I found it useful to reflect on the way the previous studies were designed and what considerations I have made. Randomized trials are only as good as they are designed - and important considerations must be made prior to the initiation of the project. Often recruitment of patients may last for years and therefore a careful plan is needed to enhance the scientific outcome of the study. Conventional randomized trials are designed so that they will provide a meaningful answer on its own (definitive stand-alone study), adresses a superiority question, allocates patients in a 1:1 ratio to two parallel study groups.(1)

# Choosing the best primary endpoint
Since the sample size estimation and the conclusion of the study is based on what was choosen as primary endpoint it is of outmost importance to deside on the primary endpoint a priori. Also, the endpoint must be meaningful to clinicians, so that the results can be implemented in practise and provide not just evidence but useful information. The primary endpoint must be a variable were it is meaningful to calculate and detect a difference, i.e. **effect size**. One must deside on choosing an endpoint that is realistic to clinicians or an endpoint that is realistic to the current evidence and in-line with previous studies. Ideal the endpoint is realistic to both. As a further guidance the principe of "the minimal difference important to patients."(2) Consequently, even a minimal difference can be relevant, when the endpoint is e.g. deaths (mortality) or major cardiovascular events. 
=======
On my way to design a third and fourth clinical trial I found it useful to reflect on the way the previous studies were designed and what considerations I have made. Randomized trials are only as good as they are designed - and important considerations must be made prior to the initiation of the project. Often recruitment of patients may last for years and therefore a careful plan is needed to enhance the scientific outcome of the study. Conventional randomized trials are designed so that they will provide a meaningful answer on its own (definitive stand-alone study), adresses a superiority question, allocates patients in a 1:1 ratio to two parallel study groups.

# Choosing the best primary endpoint
Since the sample size estimation and the conclusion of the study is based on what was choosen as primary endpoint it is of outmost importance to deside on the primary endpoint a priori. Also, the endpoint must be meaningful to clinicians, so that the results can be implemented in practise and provide not just evidence but useful information. The primary endpoint must be a variable were it is meaningful to calculate and detect a difference, i.e. **effect size**. One must deside on choosing an endpoint that is realistic to clinicians or an endpoint that is realistic to the current evidence and in-line with previous studies. Ideal the endpoint is realistic to both. As a further guidance the principe of "the minimal difference important to patients."
>>>>>>> 1e06dd418cda2dd956f3b04609829e6c96ff2fe0

For cardioversion trials the endpoint is often "cardioversion efficacy", i.e. the proportion of patients with a successful treatment outcome. This endpoint has many advantages and we desided on using **cardioversion outcome** since it provides crusial benefits: 

   - It a variable, were a difference can be meassured and is clinical meaningful
   - It a dicotomous outcome, which is very robust, and can be documented on an electrocardiogram

Then, for the individual trials a taget difference must be determined.      
         
# Sample size estimation

For estimating the trial size I use the `power.prop.test` function in *R*. Considering a hypothesis where the estimated success in the control group is 85% and 95% in the experimental group, i.e. an effect size of 10%. 

```{r echo=TRUE, message=FALSE, warning=FALSE, paged.print=FALSE}

power.prop.test(p1 = 0.95,                      #p1 = proportion in control group
                p2 = 0.85,                      #p2 = propottion in the experimental group
                sig.level = 0.05,               #choose significance level, standard is 0.05 (alfa value)
                power = 0.80,                   #choose power (beta value)
                alternative = c("two.sided"),   
                n = NULL
                )

```
<<<<<<< HEAD

## References

1. Cook JA, Hislop J, Altman DG, et al. Specifying the target difference in the primary outcome for a randomised controlled trial: guidance for researchers. Trials. 2015;16(1). doi:10.1186/s13063-014-0526-8

2. Beaton DE, Boers M, Wells GA. Many faces of the minimal clinically important difference (MCID): a literature review and directions for future research. Current Opinion in Rheumatology. 2002;14(2):109.

=======
>>>>>>> 1e06dd418cda2dd956f3b04609829e6c96ff2fe0
